ERROR - 2022-11-29 00:09:18 --> mysqli_sql_exception: Illegal mix of collations (latin1_swedish_ci,IMPLICIT) and (utf8_general_ci,COERCIBLE) for operation '=' in /home/u1606672/public_html/form/system/Database/MySQLi/Connection.php:292
Stack trace:
#0 /home/u1606672/public_html/form/system/Database/MySQLi/Connection.php(292): mysqli->query('SELECT name, si...', 0)
#1 /home/u1606672/public_html/form/system/Database/BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('SELECT name, si...')
#2 /home/u1606672/public_html/form/system/Database/BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT name, si...')
#3 /home/u1606672/public_html/form/app/Controllers/Home.php(186): CodeIgniter\Database\BaseConnection->query('SELECT name, si...')
#4 /home/u1606672/public_html/form/system/CodeIgniter.php(927): App\Controllers\Home->approve()
#5 /home/u1606672/public_html/form/system/CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#6 /home/u1606672/public_html/form/system/CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 /home/u1606672/public_html/form/public/index.php(67): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-11-29 00:09:18 --> Uncaught ErrorException: realpath() expects parameter 1 to be a valid path, string given in /home/u1606672/public_html/form/system/Common.php:90
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'realpath() expe...', '/home/u1606672/...', 90, Array)
#1 /home/u1606672/public_html/form/system/Common.php(90): realpath('SELECT name, si...')
#2 /home/u1606672/public_html/form/system/Debug/Exceptions.php(516): clean_path('SELECT name, si...')
#3 [internal function]: CodeIgniter\Debug\Exceptions::CodeIgniter\Debug\{closure}('SELECT name, si...')
#4 /home/u1606672/public_html/form/system/Debug/Exceptions.php(521): array_map(Object(Closure), Array)
#5 /home/u1606672/public_html/form/system/Debug/Exceptions.php(115): CodeIgniter\Debug\Exceptions::renderBacktrace(Array)
#6 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(mysqli_sql_exception))
#7 {main}
  thrown
in SYSTEMPATH/Common.php on line 90.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
